import type { MetadataRoute } from "next";

/*
 * robots.txt — generated by Next.js metadata route.
 * PiekAI is an AI-visibility product, so AI crawlers (GPTBot, ClaudeBot,
 * PerplexityBot, …) are deliberately allowed alongside classic search bots.
 * Only the auth flow is disallowed — it carries no indexable content.
 */
const SITE_URL = "https://piekai.nl";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/auth/"],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
