import type { MetadataRoute } from "next";
import { getAllPosts } from "@/lib/journal";

/*
 * sitemap.xml — generated by Next.js metadata route.
 * Lists public marketing pages plus every published Journal post.
 * Auth pages and error routes are intentionally excluded.
 */
const SITE_URL = "https://piekai.nl";

/** Static, indexable marketing routes with a relative priority. */
const STATIC_ROUTES: ReadonlyArray<{ path: string; priority: number }> = [
  { path: "/", priority: 1.0 },
  { path: "/prijzen", priority: 0.9 },
  { path: "/methodologie", priority: 0.8 },
  { path: "/over-ons", priority: 0.7 },
  { path: "/journal", priority: 0.7 },
  { path: "/contact", priority: 0.6 },
  { path: "/status", priority: 0.3 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticEntries: MetadataRoute.Sitemap = STATIC_ROUTES.map((route) => ({
    url: `${SITE_URL}${route.path}`,
    lastModified: now,
    changeFrequency: "monthly",
    priority: route.priority,
  }));

  const postEntries: MetadataRoute.Sitemap = getAllPosts().map((post) => ({
    url: `${SITE_URL}/journal/${post.slug}`,
    lastModified: new Date(`${post.date}T12:00:00Z`),
    changeFrequency: "yearly",
    priority: 0.5,
  }));

  return [...staticEntries, ...postEntries];
}
